// An Arma 3 server only auto-starts a mission that is both present on disk and
// named by a `class Missions` entry in server.cfg. Mods can also register
// missions through their own CfgMissions, where nothing on disk reveals them —
// Antistasi does exactly that — so a template must also be typeable.
const fs = require('fs');
const path = require('path');
const os = require('os');
const { source, grab, makeCheck, report } = require('./helpers/source');
const { check, state } = makeCheck();

const SRC = source('main.js');
const mod = {};
new Function('exports', 'fs', 'path',
  ['function armaCfgDepth(', 'function parseArmaCfg(', 'function listArmaMissions(', 'function setArmaMissionBlock(']
    .map(sig => grab(SRC, sig)).join('\n') +
  '\nexports.list = listArmaMissions; exports.setBlock = setArmaMissionBlock; exports.parse = parseArmaCfg;')(mod, fs, path);
const { list, setBlock, parse } = mod;

// ── discovery ───────────────────────────────────────────────────────────────
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'arma3-missions-'));
const inst = path.join(tmp, 'server');
const touch = (...p) => { fs.mkdirSync(path.dirname(path.join(...p)), { recursive: true }); fs.writeFileSync(path.join(...p), 'x'); };

fs.mkdirSync(path.join(inst, 'mpmissions'), { recursive: true });
touch(inst, 'mpmissions', 'MyMission.Altis.pbo');
// An unpacked mission counts only when the folder holds mission.sqm.
touch(inst, 'mpmissions', 'Unpacked.Stratis', 'mission.sqm');
fs.mkdirSync(path.join(inst, 'mpmissions', 'NotAMission.Folder'), { recursive: true });
// Missions bundled inside mods, in both casings mods use.
touch(inst, 'mods', '@Antistasi', 'mpmissions', 'Antistasi.Altis.pbo');
touch(inst, 'mods', '@Other', 'MPMissions', 'Extra.Malden.pbo');

const found = list({ installDir: inst });
const names = found.map(m => m.template).sort();
check('finds every mission', names, ['Antistasi.Altis', 'Extra.Malden', 'MyMission.Altis', 'Unpacked.Stratis']);
check('ignores a folder without mission.sqm', names.includes('NotAMission.Folder'), false);
check('strips the .pbo extension', found.find(m => m.template === 'MyMission.Altis').file, 'MyMission.Altis.pbo');
check('records the owning mod', found.find(m => m.template === 'Antistasi.Altis').source, '@Antistasi');
check('records server-owned missions', found.find(m => m.template === 'MyMission.Altis').source, 'server');
check('finds MPMissions as well as mpmissions', names.includes('Extra.Malden'), true);
check('a missing install dir is survivable', list({ installDir: path.join(tmp, 'nope') }), []);
check('no duplicate templates', new Set(names).size, names.length);

// ── writing class Missions ──────────────────────────────────────────────────
// The seed config Omnex generates ends with a one-line `class Missions {};`.
const SEED = [
  '// Generated by Omnex — edit freely.',
  'hostname = "My Server";',
  'maxPlayers = 32;',
  'verifySignatures = 2;',
  'motd[] = {"Managed by Omnex"};',
  '',
  'class Missions {};',
  '',
].join('\n');

const out1 = setBlock(SEED, 'Antistasi.Altis', 'Veteran');
check('replaces the one-line block', /class Missions \{\};/.test(out1), false);
check('writes the template', /template = "Antistasi\.Altis";/.test(out1), true);
check('writes the difficulty', /difficulty = "Veteran";/.test(out1), true);
check('leaves exactly one Missions block', (out1.match(/class Missions/g) || []).length, 1);
const sp = parse(out1);
check('top-level keys survive', [sp.hostname, sp.maxPlayers, sp.verifySignatures], ['My Server', '32', '2']);
check('nested template is not hoisted', 'template' in sp, false);
check('array key survives', /^motd\[\] = \{"Managed by Omnex"\};$/m.test(out1), true);

// A hand-written multi-line block must be replaced wholesale, not doubled.
const MULTI = [
  'hostname = "X";',
  'class Missions {',
  '    class old {',
  '        template = "Old.Altis";',
  '        difficulty = "Recruit";',
  '    };',
  '};',
  'maxPlayers = 10;',
].join('\n');
const out2 = setBlock(MULTI, 'New.Malden', 'Regular');
check('replaces a multi-line block', (out2.match(/class Missions/g) || []).length, 1);
check('the old template is gone', /Old\.Altis/.test(out2), false);
check('the new template is present', /template = "New\.Malden";/.test(out2), true);
check('a key after the block survives', parse(out2).maxPlayers, '10');
check('a key before the block survives', parse(out2).hostname, 'X');

check('appends when there is no block', (setBlock('hostname = "Y";\n', 'A.Altis', 'Regular').match(/class Missions/g) || []).length, 1);
check('appending keeps existing keys', parse(setBlock('hostname = "Y";\n', 'A.Altis', 'Regular')).hostname, 'Y');

// Re-applying must swap the mission, not stack blocks.
const twice = setBlock(setBlock(SEED, 'A.Altis', 'Regular'), 'B.Malden', 'Veteran');
check('re-applying keeps one block', (twice.match(/class Missions/g) || []).length, 1);
check('re-applying uses the newest mission', /template = "B\.Malden";/.test(twice), true);
check('quotes in a template are neutralised', /template = "Evil\.Altis";/.test(setBlock(SEED, 'Evil".Altis', 'Regular')), true);

// ── the typed-template guard ────────────────────────────────────────────────
// A mod-registered mission cannot be discovered, so a well-formed template is
// accepted on trust — but it is still validated, since it lands in server.cfg.
const guardSrc = SRC.match(/if \(!chosen && !\/(.+?)\/\.test\(String\(template/);
check('the guard exists', !!guardSrc, true);
const guard = new RegExp(guardSrc[1]);
check('accepts a discovered-style template', guard.test('Antistasi_Malden.Malden'), true);
check('accepts a plain template', guard.test('Antistasi.Altis'), true);
check('accepts hyphens', guard.test('My-Mission.Tanoa'), true);
check('rejects empty', guard.test(''), false);
check('rejects a bare name', guard.test('Antistasi'), false);
check('rejects path traversal', guard.test('../../etc.passwd'), false);
check('rejects backslashes', guard.test('a\\b.Altis'), false);
check('rejects spaces', guard.test('My Mission.Altis'), false);
check('copy step is guarded for undiscovered templates', SRC.includes("if (chosen && chosen.source !== 'server') {"), true);

fs.rmSync(tmp, { recursive: true, force: true });
report(state);
